language: R
cache: packages
sudo: required
dist: trusty
os:
  - linux
  - osx
  - windows
addons:
  apt:
    packages:
      - libv8-3.14-dev
      - libudunits2-dev

r:
  - release
  - devel
  
warnings_are_errors: false
